### ISSUE TITLE
Why does keys() not work same as keys() for dict. Returns KeysView instead

### ISSUE THREAD

**Issue by jj-github-jj** [LarsHill/metadict#8]
dict.keys() returns list but using .keys() function with metadict returns KeysView object

**Comment by LarsHill** [comment]
Hi,

`dict.keys()` does actually not return a `list` but a `dict_keys` (dictionary view) object. See [here](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects) for more infos. 

`MetaDict` also returns a dictionary view object.
```python
from metadict import MetaDict
print(isinstance({}.keys(), type(MetaDict(a=1).keys())))
>> True
```

So the return type of `MetaDict.keys()` is compatible to `dict.keys()`.
