### ISSUE TITLE
keys() returns KeysView instead of dict_keys

### ISSUE THREAD

**Issue by jj-github-jj** [LarsHill/metadict#9]
keys() returns KeysView object instead of keys.
This suggests a possible solution that I have not tried.
 https://stackoverflow.com/questions/42366856/keysview-valuesview-and-itemsview-default-representation-of-a-mapping-subclass

```
# test metadict
my_dict = MetaDict({'a': 1, 'b': 2})
print(my_dict)
my_dict.keys()

my_dict = dict({'a': 1, 'b': 2})
print(my_dict)
my_dict.keys()

# output is
#{'a': 1, 'b': 2}
#KeysView({'a': 1, 'b': 2})
#{'a': 1, 'b': 2}
#dict_keys(['a', 'b'])
```

**Comment by LarsHill** [comment]
Hi,
I replied already to a similar issue you opened on January 20th. See here (https://github.com/LarsHill/metadict/issues/8).
It seems that the only difference is the resulting `repr` if you print the returned object. If you only want to see the actual keys printed out, you can do `print(list(my_dict))`.
I don't plan to change the current implementation.

**Comment by jj-github-jj** [comment]
Sorry for the repeat didn't remember.  If the overview doc could adda a
comment/usage tip regarding this one usage difference that can help future
novices like me. Thanks
